name: Publish Prod

on:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build & Lint & Test
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
          scope: "@one-bridge"

      - name: Install dependencies
        run: npm ci

      - name: Npm version
        run: cd ./dist && npm version --no-git-tag-version 4.1.6

      - name: Build
        env:
          NODE_ENV: "production"
        run: |
          npm install -g browserify@17.0.0
          npm install -g minify@10.3.0
          npm install -g less@4.2.0
          npm run bundle-apg-conv-api
          npm run bundle-apg-lib
          npm run bundle-apg-api
          npm run bundle-apg-exp
          npm run bundle-apg-lib-css

      - name: Publish
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

